#!/bin/sh
#
# ~/.xinitrc
#
#python ~/.config/youtube-local/server.py &

# USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
# USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
# ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"
# ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"
# localectl set-x11-keymap us '' '' caps:escape

dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY&
python ~/.local/share/youtube-local/server.py &
xset b off &
librewolf -P default &
find &
[[ -f ~/.xmodmap-jack ]] && xmodmap ~/.xmodmap-jack

# Starting window manager
exec i3
