#!/bin/sh
#
# ~/.xinitrc
#
#python ~/.config/youtube-local/server.py &

# USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
# USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
# ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"
# ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY&
setxkbmap -option caps:swapescape &
xset b off &

nm-applet &

# Starting window manager
exec i3
