#!/bin/sh

setxkbmap -option caps:swapescape &
picom &
polywal &
xss-lock -- slock &
unclutter --timeout 1 &
dwmstat &

python ~/code/yt-local/server.py &
killall -q rep 
rep 5 "bat-stat" &
rep 1800 "newsboat -x reload" &
gummy start &
gummy -T 1 -y 06:00 -u 16:30 -k 3000 -j 5000 &
brightnessctl s 20% &
aw-server &
nm-applet &
dunst &
typeracer

#shutdown -P 20:00 &
#time=$(date '+%H')
#if [ "$time" -gt 20 ] || [ "$time" -lt 5 ];then
#   shutdown now 
#fi

while type dwm >/dev/null ; do dwm && continue || break ; done
