#!/bin/sh

#code to shutdown linux at certaintimes
#shutdown -P 21:00 &
#time=$(date '+%H')
#if [ "$time" -gt 21 ] || [ "$time" -lt 8 ]; then
#   shutdown now
#fi

# Executed by startx (run your window manager from here)
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY&
setxkbmap -option caps:swapescape &
thunar --daemon &
xset b off &
picom -f --experimental-backends &
dunst &
nm-applet &
mpd &
picom -f --experimental-backends &
xss-lock -- i3lock -c 000000 -R 1000 -F 100 -O 0 -o ffffff -l ffffff --no-keyboard-layout -T 1 &
xbacklight -set 20 &
dunst &
unclutter --timeout 1 &
mpDris2 &
nmcli connection up JioFiber-Home5G &
polywal &
exec i3
