#!/bin/sh

while read file
do
    case "$1" in
       "b") feh --bg-fill $file && mv ~/.fehbg ~/.config/i3/scripts/fehbg.sh;;
       "d") gio trash $file;;
       "p") polywal "$file" &;;
       "r") rm -rf ~/.cache/nsxiv;;
    esac
done
