#!/bin/sh

__invidious_search_json_videos () {
	jq '
	def pad_left(n; num):
		num | tostring |
			if (n > length) then ((n - length) * "0") + (.) else . end
		;
	[ .[] | select(.type=="shortVideo") |
		{
			scraper: "invidious_search",
			ID: .videoId,
			url: "https://vid.puffyan.us/watch?v=\(.videoId)",
			title: .title,
			channel: .author,
			thumbs: "'"${invidious_instance}"'/vi/\(.videoId)/'"$thumbnail_quality"'.jpg",
			duration: "\(.lengthSeconds / 60 | floor):\(pad_left(2; .lengthSeconds % 60))",
			views: "\(.viewCount)",
			date: .publishedText,
			description: .description
		}
	]'
}

scrape_invidious_popular(){
    search="$1"
    output_json_file="$2"

    echo "scraping invidious popular"
   while [ "${i:=1}" -le "$pages_to_scrape" ]; do
	_tmp_json="${session_temp_dir}/invidious-popular-$i.json"

	[ "$invidious_instance" = "https://vid.puffyan.us" ] && invidious_instance="https://vid.puffyan.us"
	_get_request "$invidious_instance/api/v1/popular" \
	    -G --data-urlencode "page=$1" --compressed > "$_tmp_json"

	_get_invidious_thumb_quality_name

	{
	    _invidious_search_json_live < "$_tmp_json"
	    __invidious_search_json_videos < "$_tmp_json"
	    _invidious_search_json_channel < "$_tmp_json"
	    _invidious_search_json_playlist < "$_tmp_json"
	} >> "$output_json_file"
	i=$((i+1))
    done
    unset i output_json_file
}
