[terminal.shell]
program = "/bin/fish"
args = ["--login", "-c", "cd /mnt/PS/ && exec fish"]
[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"
foreground = "#a9b1d6"

[colors.normal]
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#787c99"

[colors.bright]
black = "#444b6a"
red = "#ff7a93"
green = "#b9f27c"
yellow = "#ff9e64"
blue = "#7da6ff"
magenta = "#bb9af7"
cyan = "#0db9d7"
white = "#acb0d0"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "Hack Nerd Font"
style = "Regular"

[font.bold_italic]
family = "SauceCodePro NF"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro NF"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 5000

[window]
dynamic_padding = false
opacity = 0.6
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6

[terminal]
