# Prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"

# Shell
set -g default-shell /usr/bin/fish

# Mouse
set -g mouse on

# Splits
bind | split-window -h
bind - split-window -v

# Kill pane
bind q kill-pane

# Terminal + truecolor
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:Tc"

# Vim movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Titles
set -g set-titles on

# Minimal status bar
set -g status-position bottom
set -g status-justify left

set -g status-style "bg=#000000,fg=#ffffff"
set -g status-right "#[fg=#ffffff]#(date +'%H:%M')"

set -g status-left ""

set -g status-left-length 0
set -g status-right-length 20

set -g status on
